#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import time

def process_chrome_cookies(input_file, output_file):
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    with open(output_file, 'w', encoding='utf-8') as f:
        # Netscape cookie formatı başlığı
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
        f.write("# This file was generated by cookie_converter.py\n\n")
        
        # Her satırı işle
        for line in lines:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            
            parts = line.split('\t')
            if len(parts) >= 5:
                try:
                    name = parts[0]
                    value = parts[1]
                    domain = parts[2]
                    path = parts[3]
                    expiry = int(time.time()) + 86400*30  # 30 gün
                    secure = "TRUE" if "TRUE" in line.upper() or "SECURE" in line.upper() else "FALSE"
                    
                    # Domain'i düzelt
                    if not domain.startswith('.') and '.' in domain:
                        domain = '.' + domain
                    
                    # Netscape formatı: domain TAB flag TAB path TAB secure TAB expiry TAB name TAB value
                    f.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
                except Exception as e:
                    sys.stderr.write(f"Satır işlenirken hata: {line} - {str(e)}\n")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Kullanım: python cookie_converter.py chrome_cookies.txt")
        print("Chrome Developer Tools -> Application -> Storage -> Cookies'den kopyalayıp bir metin dosyasına yapıştırın")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = "netscape_cookies.txt"
    process_chrome_cookies(input_file, output_file)
    print(f"Cookie'ler {output_file} dosyasına Netscape formatında kaydedildi!")
