version: '3.8'

services:
  # Python FastAPI Backend service
  backend:
    build:
      context: ./new_backend
      dockerfile: Dockerfile
      network: host
      args:
        BUILDKIT_INLINE_CACHE: 1
        DOCKER_BUILDKIT: 1
    container_name: youtube-fastapi-backend
    restart: unless-stopped
    ports:
      - "80:8000"
    environment:
      - API_V1_STR=/api/v1
      - PROJECT_NAME=YouTube Downloader API
      - DOWNLOAD_PATH=/app/downloads
      - FILE_EXPIRY_SECONDS=300
      - MAX_RESOLUTION=1080p
      - BACKEND_CORS_ORIGINS=[]
      - DEBUG=false
    volumes:
      - backend_downloads:/app/downloads
    deploy:
      resources:
        limits:
          memory: 512M
    dns:
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/youtube/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  backend_downloads: 