version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: youtube-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - DOWNLOAD_TEMP_DIR=/app/data
      - CORS_ORIGIN=http://84.8.157.166,https://84.8.157.166
      - YT_DLP_PATH=/usr/local/bin/yt-dlp
    volumes:
      - backend_data:/app/data
      - backend_public:/app/public
      - ./backend/youtube_cookies.txt:/app/youtube_cookies.txt
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: youtube-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://84.8.157.166/api
      - VITE_API_BASE_URL=http://84.8.157.166
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  backend_data:
  backend_public: 