version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: youtube-backend
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - DOWNLOAD_TEMP_DIR=/app/data
      - YT_DLP_PATH=/usr/local/bin/yt-dlp
    restart: unless-stopped 