name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      - name: Install dependencies
        run: cd backend && npm ci

      - name: Lint
        run: cd backend && npm run lint

      - name: Build
        run: cd backend && npm run build

    # Optionally, you can add a step to run tests if you want to include them in CI
    # - name: Test
    #   run: cd backend && npm test
