#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import time
import os

def process_chrome_cookies(input_file, output_file):
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        with open(output_file, 'w', encoding='utf-8') as f:
            # Netscape cookie formatı başlığı
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
            f.write("# This file was generated by cookie_converter.py\n\n")
            
            # Her satırı işle
            for line in lines:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                
                parts = line.split('\t')
                if len(parts) >= 5:
                    try:
                        name = parts[0]
                        value = parts[1]
                        domain = parts[2]
                        path = parts[3]
                        expiry = int(time.time()) + 86400*30  # 30 gün
                        secure = "TRUE" if "TRUE" in line.upper() or "SECURE" in line.upper() else "FALSE"
                        
                        # Domain'i düzelt
                        if not domain.startswith('.') and '.' in domain:
                            domain = '.' + domain
                        
                        # Netscape formatı: domain TAB flag TAB path TAB secure TAB expiry TAB name TAB value
                        f.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
                    except Exception as e:
                        sys.stderr.write(f"Satır işlenirken hata: {line} - {str(e)}\n")
        
        print(f"✅ Cookie'ler başarıyla {output_file} dosyasına kaydedildi!")
        return True
    except Exception as e:
        print(f"❌ Hata: {str(e)}")
        return False

def main():
    if len(sys.argv) != 2:
        print("""
🍪 Chrome Cookie -> Netscape Format Dönüştürücü 🍪
Kullanım: python cookie_converter.py chrome_cookies.txt

1. Chrome tarayıcınızı açın
2. YouTube'a gidin ve hesabınıza giriş yapın
3. F12 tuşuna basarak Developer Tools'u açın
4. "Application" sekmesine tıklayın
5. Sol tarafta "Storage" > "Cookies" > "https://www.youtube.com" seçin
6. Tüm cookie'leri seçin (Ctrl+A veya ⌘+A) ve kopyalayın
7. chrome_cookies.txt dosyasına yapıştırın
8. Bu scripti çalıştırın: python cookie_converter.py chrome_cookies.txt
""")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), "youtube_cookies.txt")
    process_chrome_cookies(input_file, output_file)

if __name__ == "__main__":
    main()
