name: Backend CI

on:
  push:
    branches: [main, master]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "backend/package.json"

      - name: Install dependencies
        run: cd backend && npm install

      - name: Lint
        run: cd backend && npm run lint:fix

      - name: Test
        run: cd backend && npm run test

      - name: Build
        run: cd backend && npm run build
